name: slider_2_builder
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  lib_msaadev:
    git:
      url: https://github.com/msaadev/lib_msaadev

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/dummy/
    - assets/images/
